export enum IpcChannels {
  DAMAGE_DATA = 'DAMAGE_DATA',
  NEWZONE = 'NEW_ZONE',
  CONNECTION_LOST = 'CONNECTION_LOST',
  CLOSE = 'CLOSE',
  NEW_ENCOUNTER = 'NEW_ENCOUNTER',
  CLEAR_ALL = 'CLEAR_ALL',
}
