export enum IpcChannels {
  DAMAGE_DATA = 'DAMAGE_DATA',
  NEWZONE = 'NEW_ZONE',
  CONNECTION_LOST = 'CONNECTION_LOST',
  CLOSE = 'CLOSE',
  CLOSE_WINDOW = 'CLOSE_WINDOW',
  NEW_ENCOUNTER = 'NEW_ENCOUNTER',
  CLEAR_ALL = 'CLEAR_ALL',
  ENABLE_MOUSE_PASSTHROUGH = 'ENABLE_MOUSE_PASSTHROUGH',
  DISABLE_MOUSE_PASSTHROUGH = 'DISABLE_MOUSE_PASSTHROUGH',
  OPEN_STATS_WINDOW = 'OPEN_STATS_WINDOW',
}
